### ISSUE TITLE
shows "added" button when video URL is attached to a recording and no releases

### ISSUE THREAD

**Issue by UltimateRiff** [RustyNova016/MusicBrainz-UserScripts#4]
it might make sense to check that the entities related to the URL are releases and not just standalone recordings. for example:

https://www.youtube.com/watch?v=vikINVCvqCE is related to this recording: https://musicbrainz.org/recording/dc42c303-02f2-4771-b909-fe31bb164f79, and it's showing the release as Added on YouTube

![image](https://github.com/RustyNova016/MusicBrainz-UserScripts/assets/100507157/3c82262d-d551-474d-9779-3422a31fb3ef)

**Comment by RustyNova016** [comment]
Currently the check look if the URL exist in Musicbrainz, but don't care about what it is attached to. 
So what I understand is that only Release should count as added to MB?

**Comment by UltimateRiff** [comment]
in my mind, yes, since this is a release adder 😉
